// 综合应用任务 - 6个复合应用任务数据结构
// 每个任务使用≥2个技能点

export const comprehensiveTasks = {
  // 任务1: 数据采集+数据清洗+基础运算
  'task-comprehensive-1': {
    taskId: 'task-comprehensive-1',
    skillPoint: '综合应用',
    level: '中级',
    title: '电商销售数据采集与分析',
    description: '采集电商销售数据，清洗缺失值和异常值，并计算关键指标',
    initialData: {
      sheetName: '电商销售',
      cellData: {
        'A1': { v: '订单ID' },
        'B1': { v: '日期' },
        'C1': { v: '产品' },
        'D1': { v: '数量' },
        'E1': { v: '单价' },
        'F1': { v: '金额' },
        'A2': { v: 'O001' },
        'B2': { v: '2023-01-01' },
        'C2': { v: '产品A' },
        'D2': { v: 2 },
        'E2': { v: 100 },
        'A3': { v: 'O002' },
        'B3': { v: '2023-01-02' },
        'C3': { v: '产品B' },
        'D3': { v: 3 },
        'E3': { v: 150 },
        'A4': { v: 'O003' },
        'B4': { v: '2023-01-03' },
        'C4': { v: '产品A' },
        'D4': { v: 1 },
        'E4': { v: 100 },
        'A5': { v: 'O004' },
        'B5': { v: '2023-01-04' },
        'C5': { v: '产品C' },
        'D5': { v: null },
        'E5': { v: 200 },
        'A6': { v: 'O005' },
        'B6': { v: '2023-01-05' },
        'C6': { v: '产品B' },
        'D6': { v: 5 },
        'E6': { v: 150 },
        'H1': { v: '数据清洗与计算' },
        'H2': { v: '总订单数' },
        'H3': { v: '总销售额' },
        'H4': { v: '平均订单金额' },
        'H5': { v: '最畅销产品' }
      },
      rowCount: 20,
      columnCount: 10
    },
    targetCells: ['F2:F6', 'I2:I5'],
    validationRules: {
      'F2': { type: 'value', expectedValue: 200, tolerance: 0.01 },
      'F3': { type: 'value', expectedValue: 450, tolerance: 0.01 },
      'F4': { type: 'value', expectedValue: 100, tolerance: 0.01 },
      'F5': { type: 'value', expectedValue: 200, tolerance: 0.01 },
      'F6': { type: 'value', expectedValue: 750, tolerance: 0.01 },
      'I2': { type: 'value', expectedValue: 5, tolerance: 0.01 },
      'I3': { type: 'value', expectedValue: 1700, tolerance: 0.01 },
      'I4': { type: 'value', expectedValue: 340, tolerance: 0.01 },
      'I5': { type: 'value', expectedValue: '产品B', tolerance: 0.01 }
    },
    hints: [
      '首先计算金额列：金额=数量×单价',
      '使用AVERAGE计算缺失值的填充值',
      '使用COUNT函数计算总订单数',
      '使用SUM函数计算总销售额',
      '使用MODE函数查找最畅销产品'
    ],
    steps: [
      '步骤1: 观察数据，发现D5单元格数量缺失',
      '步骤2: 在D5单元格输入"=ROUND(AVERAGE(D2:D4,D6),0)"，用平均值填充缺失值',
      '步骤3: 在F2单元格输入"=D2*E2"，计算订单金额',
      '步骤4: 向下拖动填充柄到F6，计算所有订单金额',
      '步骤5: 在I2单元格输入"=COUNTA(A2:A6)"，计算总订单数',
      '步骤6: 在I3单元格输入"=SUM(F2:F6)"，计算总销售额',
      '步骤7: 在I4单元格输入"=I3/I2"，计算平均订单金额',
      '步骤8: 在I5单元格输入"=MODE(C2:C6)"，查找最畅销产品',
      '步骤9: 检查所有计算结果是否正确',
      '步骤10: 提交任务，验证结果'
    ]
  },

  // 任务2: 数据整理+高级查询+图表制作
  'task-comprehensive-2': {
    taskId: 'task-comprehensive-2',
    skillPoint: '综合应用',
    level: '中级',
    title: '季度销售报表制作',
    description: '整理季度销售数据，使用高级查询功能，制作可视化图表',
    initialData: {
      sheetName: '季度销售',
      cellData: {
        'A1': { v: '月份' },
        'B1': { v: '产品' },
        'C1': { v: '地区' },
        'D1': { v: '销售额' },
        'A2': { v: '1' },
        'B2': { v: '产品A' },
        'C2': { v: '北京' },
        'D2': { v: 1000 },
        'A3': { v: '1' },
        'B3': { v: '产品B' },
        'C3': { v: '上海' },
        'D3': { v: 1500 },
        'A4': { v: '2' },
        'B4': { v: '产品A' },
        'C4': { v: '上海' },
        'D4': { v: 1200 },
        'A5': { v: '2' },
        'B5': { v: '产品B' },
        'C5': { v: '北京' },
        'D5': { v: 1800 },
        'A6': { v: '3' },
        'B6': { v: '产品A' },
        'C6': { v: '北京' },
        'D6': { v: 1100 },
        'A7': { v: '3' },
        'B7': { v: '产品B' },
        'C7': { v: '上海' },
        'D7': { v: 1600 },
        'F1': { v: '产品销售查询' },
        'F2': { v: '选择产品' },
        'G2': { v: '产品A' },
        'F3': { v: '总销售额' },
        'F4': { v: '最高月份' },
        'F5': { v: '最低月份' }
      },
      rowCount: 20,
      columnCount: 10
    },
    targetCells: ['G3:G5', 'A10'],
    validationRules: {
      'G3': { type: 'value', expectedValue: 3300, tolerance: 0.01 },
      'G4': { type: 'value', expectedValue: 2, tolerance: 0.01 },
      'G5': { type: 'value', expectedValue: 3, tolerance: 0.01 },
      'A10': { type: 'value', expectedValue: '图表' }
    },
    hints: [
      '使用SUMIFS函数按产品查询总销售额',
      '使用INDEX-MATCH查找最高和最低销售额对应的月份',
      '选择产品A的数据制作折线图'
    ],
    steps: [
      '步骤1: 在G3单元格输入"=SUMIFS(D2:D7,B2:B7,G2)"，计算产品A的总销售额',
      '步骤2: 在G4单元格输入"=INDEX(A2:A7,MATCH(MAX(IF(B2:B7=G2,D2:D7)),D2:D7,0))"',
      '步骤3: 在G5单元格输入"=INDEX(A2:A7,MATCH(MIN(IF(B2:B7=G2,D2:D7)),D2:D7,0))"',
      '步骤4: 筛选出产品A的数据（A2:D7中B列=产品A）',
      '步骤5: 选择筛选后的月份和销售额数据',
      '步骤6: 插入折线图，展示产品A的月度销售趋势',
      '步骤7: 调整图表标题和格式',
      '步骤8: 检查查询结果和图表是否正确',
      '步骤9: 提交任务，验证结果'
    ]
  },

  // 任务3: 数据透视分析+统计推断+预测模型
  'task-comprehensive-3': {
    taskId: 'task-comprehensive-3',
    skillPoint: '综合应用',
    level: '高级',
    title: '销售数据分析与预测',
    description: '使用数据透视表分析数据，进行统计推断，并预测下季度销售额',
    initialData: {
      sheetName: '销售预测',
      cellData: {
        'A1': { v: '季度' },
        'B1': { v: '产品' },
        'C1': { v: '地区' },
        'D1': { v: '销售额' },
        'A2': { v: 'Q1' },
        'B2': { v: '产品A' },
        'C2': { v: '北京' },
        'D2': { v: 1000 },
        'A3': { v: 'Q1' },
        'B3': { v: '产品B' },
        'C3': { v: '上海' },
        'D3': { v: 1500 },
        'A4': { v: 'Q2' },
        'B4': { v: '产品A' },
        'C4': { v: '上海' },
        'D4': { v: 1200 },
        'A5': { v: 'Q2' },
        'B5': { v: '产品B' },
        'C5': { v: '北京' },
        'D5': { v: 1800 },
        'A6': { v: 'Q3' },
        'B6': { v: '产品A' },
        'C6': { v: '北京' },
        'D6': { v: 1100 },
        'A7': { v: 'Q3' },
        'B7': { v: '产品B' },
        'C7': { v: '上海' },
        'D7': { v: 1600 },
        'F1': { v: '统计分析' },
        'F2': { v: '季度平均销售额' },
        'F3': { v: '销售额标准差' },
        'F4': { v: '产品A与B的相关系数' },
        'F5': { v: 'Q4预测销售额（产品A）' },
        'F6': { v: 'Q4预测销售额（产品B）' }
      },
      rowCount: 20,
      columnCount: 10
    },
    targetCells: ['G2:G6', 'A10'],
    validationRules: {
      'G2': { type: 'value', expectedValue: 1366.67, tolerance: 1 },
      'G3': { type: 'value', expectedValue: 314.11, tolerance: 1 },
      'G4': { type: 'value', expectedValue: 0.5, tolerance: 0.1 },
      'G5': { type: 'value', expectedValue: 1100, tolerance: 50 },
      'G6': { type: 'value', expectedValue: 1633.33, tolerance: 50 },
      'A10': { type: 'value', expectedValue: '数据透视表' }
    },
    hints: [
      '首先创建数据透视表，按季度和产品汇总销售额',
      '使用AVERAGE、STDEV、CORREL等统计函数',
      '使用移动平均法预测Q4销售额'
    ],
    steps: [
      '步骤1: 选择A1:D7数据，创建数据透视表',
      '步骤2: 将季度拖到行，产品拖到列，销售额拖到值',
      '步骤3: 在G2单元格输入"=AVERAGE(D2:D7)"，计算季度平均销售额',
      '步骤4: 在G3单元格输入"=STDEV(D2:D7)"，计算销售额标准差',
      '步骤5: 在G4单元格输入"=CORREL(IF(B2:B7=\"产品A\",D2:D7,0),IF(B2:B7=\"产品B\",D2:D7,0))"',
      '步骤6: 在G5单元格输入"=AVERAGE(1000,1200,1100)"，预测产品A Q4销售额',
      '步骤7: 在G6单元格输入"=AVERAGE(1500,1800,1600)"，预测产品B Q4销售额',
      '步骤8: 检查数据透视表和统计分析结果',
      '步骤9: 提交任务，验证结果'
    ]
  },

  // 任务4: 数组与公式+条件格式+数据验证
  'task-comprehensive-4': {
    taskId: 'task-comprehensive-4',
    skillPoint: '综合应用',
    level: '高级',
    title: '学生成绩管理系统',
    description: '使用数组公式计算成绩，设置条件格式，添加数据验证',
    initialData: {
      sheetName: '成绩管理',
      cellData: {
        'A1': { v: '学号' },
        'B1': { v: '姓名' },
        'C1': { v: '语文' },
        'D1': { v: '数学' },
        'E1': { v: '英语' },
        'F1': { v: '总分' },
        'G1': { v: '平均分' },
        'H1': { v: '等级' },
        'A2': { v: 'S001' },
        'B2': { v: '张三' },
        'C2': { v: 85 },
        'D2': { v: 92 },
        'E2': { v: 78 },
        'A3': { v: 'S002' },
        'B3': { v: '李四' },
        'C3': { v: 90 },
        'D3': { v: 88 },
        'E3': { v: 95 },
        'A4': { v: 'S003' },
        'B4': { v: '王五' },
        'C4': { v: 72 },
        'D4': { v: 65 },
        'E4': { v: 80 },
        'A5': { v: 'S004' },
        'B5': { v: '赵六' },
        'C5': { v: 95 },
        'D5': { v: 98 },
        'E5': { v: 92 },
        'J1': { v: '成绩查询' },
        'J2': { v: '选择学号' },
        'K2': { v: 'S001' }
      },
      rowCount: 20,
      columnCount: 12
    },
    targetCells: ['F2:G5', 'H2:H5', 'C2:E5'],
    validationRules: {
      'F2': { type: 'value', expectedValue: 255, tolerance: 0.01 },
      'F3': { type: 'value', expectedValue: 273, tolerance: 0.01 },
      'F4': { type: 'value', expectedValue: 217, tolerance: 0.01 },
      'F5': { type: 'value', expectedValue: 285, tolerance: 0.01 },
      'G2': { type: 'value', expectedValue: 85, tolerance: 0.01 },
      'G3': { type: 'value', expectedValue: 91, tolerance: 0.01 },
      'G4': { type: 'value', expectedValue: 72.33, tolerance: 0.01 },
      'G5': { type: 'value', expectedValue: 95, tolerance: 0.01 },
      'H2': { type: 'value', expectedValue: '良好' },
      'H3': { type: 'value', expectedValue: '优秀' },
      'H4': { type: 'value', expectedValue: '及格' },
      'H5': { type: 'value', expectedValue: '优秀' }
    },
    hints: [
      '使用数组公式同时计算总分和平均分',
      '使用IF函数嵌套计算等级：90+优秀，80-89良好，60-79及格，<60不及格',
      '设置条件格式：平均分<60红色，60-79黄色，80+绿色',
      '为K2单元格添加数据验证下拉菜单，选择学号'
    ],
    steps: [
      '步骤1: 选择F2:F5单元格区域',
      '步骤2: 输入数组公式"=C2:C5+D2:D5+E2:E5"，按Ctrl+Shift+Enter确认',
      '步骤3: 选择G2:G5单元格区域',
      '步骤4: 输入数组公式"=F2:F5/3"，按Ctrl+Shift+Enter确认',
      '步骤5: 在H2单元格输入"=IF(G2>=90,\"优秀\",IF(G2>=80,\"良好\",IF(G2>=60,\"及格\",\"不及格\")))"',
      '步骤6: 向下拖动填充柄到H5单元格',
      '步骤7: 选择G2:G5单元格，设置条件格式：<60红色填充，60-79黄色填充，80+绿色填充',
      '步骤8: 选择K2单元格，添加数据验证，来源为A2:A5的学号',
      '步骤9: 检查所有计算和设置是否正确',
      '步骤10: 提交任务，验证结果'
    ]
  },

  // 任务5: 数据清洗+高级查询+数据透视分析
  'task-comprehensive-5': {
    taskId: 'task-comprehensive-5',
    skillPoint: '综合应用',
    level: '高级',
    title: '客户订单数据分析',
    description: '清洗客户订单数据，使用高级查询功能，创建数据透视表分析',
    initialData: {
      sheetName: '客户订单',
      cellData: {
        'A1': { v: '订单号' },
        'B1': { v: '客户' },
        'C1': { v: '产品' },
        'D1': { v: '数量' },
        'E1': { v: '单价' },
        'F1': { v: '日期' },
        'A2': { v: '1001' },
        'B2': { v: '客户A' },
        'C2': { v: '产品X' },
        'D2': { v: 5 },
        'E2': { v: 100 },
        'F2': { v: '2023-01-05' },
        'A3': { v: '1002' },
        'B3': { v: '客户B' },
        'C3': { v: '产品Y' },
        'D3': { v: null },
        'E3': { v: 200 },
        'F3': { v: '2023-01-10' },
        'A4': { v: '1003' },
        'B4': { v: '客户A' },
        'C4': { v: '产品Z' },
        'D4': { v: 3 },
        'E4': { v: 150 },
        'F4': { v: '2023-01-15' },
        'A5': { v: '1004' },
        'B5': { v: '客户C' },
        'C5': { v: '产品X' },
        'D5': { v: 2 },
        'E5': { v: 100 },
        'F5': { v: '2023-01-20' },
        'A6': { v: '1005' },
        'B6': { v: '客户B' },
        'C6': { v: '产品Y' },
        'D6': { v: 4 },
        'E6': { v: 200 },
        'F6': { v: '2023-01-25' },
        'A7': { v: '1006' },
        'B7': { v: '客户A' },
        'C7': { v: '产品Y' },
        'D7': { v: 1 },
        'E7': { v: 200 },
        'F7': { v: '2023-02-01' },
        'H1': { v: '数据查询' },
        'H2': { v: '选择客户' },
        'I2': { v: '客户A' },
        'H3': { v: '总订单数' },
        'H4': { v: '总金额' },
        'H5': { v: '最常购买产品' }
      },
      rowCount: 20,
      columnCount: 10
    },
    targetCells: ['D3', 'I3:I5', 'A12'],
    validationRules: {
      'D3': { type: 'value', expectedValue: 3, tolerance: 0.01 },
      'I3': { type: 'value', expectedValue: 3, tolerance: 0.01 },
      'I4': { type: 'value', expectedValue: 1150, tolerance: 0.01 },
      'I5': { type: 'value', expectedValue: '产品Y', tolerance: 0.01 },
      'A12': { type: 'value', expectedValue: '数据透视表' }
    },
    hints: [
      '首先清洗D3的缺失值，使用其他订单数量的平均值',
      '使用COUNTIFS和SUMIFS查询客户数据',
      '创建数据透视表分析客户购买行为'
    ],
    steps: [
      '步骤1: 观察数据，发现D3单元格数量缺失',
      '步骤2: 在D3单元格输入"=ROUND(AVERAGE(D2,D4:D7),0)"，用平均值填充缺失值',
      '步骤3: 在I3单元格输入"=COUNTIFS(B2:B7,I2)"，计算客户A的总订单数',
      '步骤4: 在I4单元格输入"=SUMIFS(B2:B7,I2,D2:D7,E2:E7)"的变体，计算总金额',
      '步骤5: 在I5单元格输入"=MODE(IF(B2:B7=I2,C2:C7))"，查找最常购买产品',
      '步骤6: 创建数据透视表，将客户拖到行，产品拖到列，数量拖到值',
      '步骤7: 检查数据清洗、查询结果和透视表',
      '步骤8: 提交任务，验证结果'
    ]
  },

  // 任务6: 图表制作+动态仪表盘+商业报告
  'task-comprehensive-6': {
    taskId: 'task-comprehensive-6',
    skillPoint: '综合应用',
    level: '高级',
    title: '年度销售报告与仪表盘',
    description: '制作销售图表，创建动态仪表盘，完成完整的商业报告',
    initialData: {
      sheetName: '年度销售报告',
      cellData: {
        'A1': { v: '月份' },
        'B1': { v: '产品A' },
        'C1': { v: '产品B' },
        'D1': { v: '产品C' },
        'E1': { v: '总销售额' },
        'A2': { v: '1月' },
        'B2': { v: 1000 },
        'C2': { v: 1500 },
        'D2': { v: 800 },
        'A3': { v: '2月' },
        'B3': { v: 1200 },
        'C3': { v: 1300 },
        'D3': { v: 900 },
        'A4': { v: '3月' },
        'B4': { v: 1100 },
        'C4': { v: 1600 },
        'D4': { v: 1000 },
        'A5': { v: '4月' },
        'B5': { v: 1300 },
        'C5': { v: 1400 },
        'D5': { v: 1100 },
        'A6': { v: '5月' },
        'B6': { v: 1400 },
        'C6': { v: 1700 },
        'D6': { v: 1200 },
        'A7': { v: '6月' },
        'B7': { v: 1500 },
        'C7': { v: 1800 },
        'D7': { v: 1300 },
        'G1': { v: '仪表盘控制' },
        'G2': { v: '选择产品' },
        'H2': { v: '产品A' },
        'G3': { v: '选择月份范围' },
        'H3': { v: 1 },
        'I3': { v: 6 },
        'K1': { v: '关键指标' },
        'K2': { v: '上半年总销售额' },
        'K3': { v: '月均销售额' },
        'K4': { v: '最佳销售月份' },
        'K5': { v: '增长趋势' }
      },
      rowCount: 25,
      columnCount: 15
    },
    targetCells: ['E2:E7', 'L2:L5', 'A10', 'A15'],
    validationRules: {
      'E2': { type: 'value', expectedValue: 3300, tolerance: 0.01 },
      'E3': { type: 'value', expectedValue: 3400, tolerance: 0.01 },
      'E4': { type: 'value', expectedValue: 3700, tolerance: 0.01 },
      'E5': { type: 'value', expectedValue: 3800, tolerance: 0.01 },
      'E6': { type: 'value', expectedValue: 4300, tolerance: 0.01 },
      'E7': { type: 'value', expectedValue: 4600, tolerance: 0.01 },
      'L2': { type: 'value', expectedValue: 23100, tolerance: 0.01 },
      'L3': { type: 'value', expectedValue: 3850, tolerance: 0.01 },
      'L4': { type: 'value', expectedValue: '6月', tolerance: 0.01 },
      'L5': { type: 'value', expectedValue: '上升', tolerance: 0.01 },
      'A10': { type: 'value', expectedValue: '组合图表' },
      'A15': { type: 'value', expectedValue: '商业报告' }
    },
    hints: [
      '首先计算总销售额列',
      '使用SUM、AVERAGE、INDEX-MATCH等函数计算关键指标',
      '创建组合图表：总销售额用柱状图，各产品用折线图',
      '为H2添加数据验证下拉菜单',
      '最后整理商业报告格式'
    ],
    steps: [
      '步骤1: 在E2单元格输入"=B2+C2+D2"，计算1月总销售额',
      '步骤2: 向下拖动填充柄到E7，计算所有月份总销售额',
      '步骤3: 在L2单元格输入"=SUM(E2:E7)"，计算上半年总销售额',
      '步骤4: 在L3单元格输入"=L2/6"，计算月均销售额',
      '步骤5: 在L4单元格输入"=INDEX(A2:A7,MATCH(MAX(E2:E7),E2:E7,0))"',
      '步骤6: 在L5单元格输入"=IF(E7>E2,\"上升\",\"下降\")"',
      '步骤7: 选择A1:D7数据，创建组合图表',
      '步骤8: 为H2单元格添加数据验证，来源为B1:D1',
      '步骤9: 整理商业报告格式，添加标题、边框、条件格式',
      '步骤10: 检查所有计算、图表和报告',
      '步骤11: 提交任务，验证结果'
    ]
  }
};
